// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: pb/cart.proto

package cart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CartSeervice_AddToCart_FullMethodName          = "/cart.CartSeervice/AddToCart"
	CartSeervice_RemoveFromCart_FullMethodName     = "/cart.CartSeervice/RemoveFromCart"
	CartSeervice_UpdateCartQuantity_FullMethodName = "/cart.CartSeervice/UpdateCartQuantity"
	CartSeervice_ViewCart_FullMethodName           = "/cart.CartSeervice/ViewCart"
)

// CartSeerviceClient is the client API for CartSeervice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartSeerviceClient interface {
	AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error)
	RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, opts ...grpc.CallOption) (*RemoveFromCartResponse, error)
	UpdateCartQuantity(ctx context.Context, in *UpdateCartQuantityRequest, opts ...grpc.CallOption) (*UpdateCartQuantiyResponse, error)
	ViewCart(ctx context.Context, in *ViewCartRequest, opts ...grpc.CallOption) (*ViewCartResponse, error)
}

type cartSeerviceClient struct {
	cc grpc.ClientConnInterface
}

func NewCartSeerviceClient(cc grpc.ClientConnInterface) CartSeerviceClient {
	return &cartSeerviceClient{cc}
}

func (c *cartSeerviceClient) AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddToCartResponse)
	err := c.cc.Invoke(ctx, CartSeervice_AddToCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartSeerviceClient) RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, opts ...grpc.CallOption) (*RemoveFromCartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromCartResponse)
	err := c.cc.Invoke(ctx, CartSeervice_RemoveFromCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartSeerviceClient) UpdateCartQuantity(ctx context.Context, in *UpdateCartQuantityRequest, opts ...grpc.CallOption) (*UpdateCartQuantiyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCartQuantiyResponse)
	err := c.cc.Invoke(ctx, CartSeervice_UpdateCartQuantity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartSeerviceClient) ViewCart(ctx context.Context, in *ViewCartRequest, opts ...grpc.CallOption) (*ViewCartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewCartResponse)
	err := c.cc.Invoke(ctx, CartSeervice_ViewCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartSeerviceServer is the server API for CartSeervice service.
// All implementations must embed UnimplementedCartSeerviceServer
// for forward compatibility.
type CartSeerviceServer interface {
	AddToCart(context.Context, *AddToCartRequest) (*AddToCartResponse, error)
	RemoveFromCart(context.Context, *RemoveFromCartRequest) (*RemoveFromCartResponse, error)
	UpdateCartQuantity(context.Context, *UpdateCartQuantityRequest) (*UpdateCartQuantiyResponse, error)
	ViewCart(context.Context, *ViewCartRequest) (*ViewCartResponse, error)
	mustEmbedUnimplementedCartSeerviceServer()
}

// UnimplementedCartSeerviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCartSeerviceServer struct{}

func (UnimplementedCartSeerviceServer) AddToCart(context.Context, *AddToCartRequest) (*AddToCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedCartSeerviceServer) RemoveFromCart(context.Context, *RemoveFromCartRequest) (*RemoveFromCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromCart not implemented")
}
func (UnimplementedCartSeerviceServer) UpdateCartQuantity(context.Context, *UpdateCartQuantityRequest) (*UpdateCartQuantiyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCartQuantity not implemented")
}
func (UnimplementedCartSeerviceServer) ViewCart(context.Context, *ViewCartRequest) (*ViewCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewCart not implemented")
}
func (UnimplementedCartSeerviceServer) mustEmbedUnimplementedCartSeerviceServer() {}
func (UnimplementedCartSeerviceServer) testEmbeddedByValue()                      {}

// UnsafeCartSeerviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartSeerviceServer will
// result in compilation errors.
type UnsafeCartSeerviceServer interface {
	mustEmbedUnimplementedCartSeerviceServer()
}

func RegisterCartSeerviceServer(s grpc.ServiceRegistrar, srv CartSeerviceServer) {
	// If the following call pancis, it indicates UnimplementedCartSeerviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CartSeervice_ServiceDesc, srv)
}

func _CartSeervice_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartSeerviceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartSeervice_AddToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartSeerviceServer).AddToCart(ctx, req.(*AddToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartSeervice_RemoveFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartSeerviceServer).RemoveFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartSeervice_RemoveFromCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartSeerviceServer).RemoveFromCart(ctx, req.(*RemoveFromCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartSeervice_UpdateCartQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartSeerviceServer).UpdateCartQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartSeervice_UpdateCartQuantity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartSeerviceServer).UpdateCartQuantity(ctx, req.(*UpdateCartQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartSeervice_ViewCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartSeerviceServer).ViewCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartSeervice_ViewCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartSeerviceServer).ViewCart(ctx, req.(*ViewCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CartSeervice_ServiceDesc is the grpc.ServiceDesc for CartSeervice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartSeervice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cart.CartSeervice",
	HandlerType: (*CartSeerviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToCart",
			Handler:    _CartSeervice_AddToCart_Handler,
		},
		{
			MethodName: "RemoveFromCart",
			Handler:    _CartSeervice_RemoveFromCart_Handler,
		},
		{
			MethodName: "UpdateCartQuantity",
			Handler:    _CartSeervice_UpdateCartQuantity_Handler,
		},
		{
			MethodName: "ViewCart",
			Handler:    _CartSeervice_ViewCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/cart.proto",
}
